sources:
  - name: Heronbank Cat Rescue
    type: rss
    url: https://rss.app/feeds/8ZEez9pneLj9S3q2.xml

  - name: RSPCA Cat Rescue
    type: rss
    url: https://rss.app/feeds/WqvTyqOZkn58XvCb.xml

  - name: Button Cat Rescue
    type: rss
    url: https://rss.app/feeds/U4L2ZvemCy1ogDqG.xml

  - name: Cat Protection League
    type: rss
    url: https://rss.app/feeds/zAlOeQjKCO6LOwrj.xml

  - name: Allerton Cat Rescue
    type: rss
    url: https://rss.app/feeds/GalXjuKJ4cqS5kUa.xml

  - name: Yorkshire Cat Rescue
    type: rss
    url: https://rss.app/feeds/nKwrtGL2xzwxwuJd.xml

  - name: Pets4Homes (West Yorkshire)
    type: pets4homes
    skipFilter: true
    distance: 30
